language: node_js
node_js:
  - "node"

install:
  - npm install

before_deploy:
  - npm run build && mv build/index.html build/200.html

deploy:
  skip_cleanup: true
  provider: surge
  project: ./build
  domain: profile.mcmyler.com